Vagrant.configure("2") do |config|

	config.vm.define "server" do |server_config|
		server_config.vm.box = "debian/bookworm64"
		server_config.vm.hostname = "antgabri.S"
		server_config.vm.network "private_network", ip: "192.168.56.110"
		server_config.vm.network :forwarded_port, guest: 22, host: 2522, auto_correct: false, id: "ssh"
		server_config.ssh.host = "127.0.0.1"
		server_config.vm.provider "virtualbox" do |vb|
			vb.gui = true
			vb.name = "p1_server"
			vb.memory = "521"
			vb.cpus = 1
		end
	end
end