Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  # Redirection des ports pour ton navigateur hôte
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8443, host: 8443

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y docker.io make
    curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.6.0 bash

    usermod -aG docker vagrant
    
    cd /vagrant
    make
  SHELL
  
  config.vm.provider "virtualbox" do |vb|
  vb.memory = "4096"
  vb.cpus = 2
  end
end