apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-ingress
  namespace: gitlab
spec:
  ingressClassName: traefik
  tls:
  - hosts :
    - gitlab.localhost
    secretName: gitlab-tls-secret
  rules:
  - host: gitlab.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Values.service.name }}
            port:
              number: 80